<?php
/**
 * CompanyManagementSummaryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Company
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Company API
 *
 * ConnectWise Company API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Company;

/**
 * CompanyManagementSummaryTest Class Doc Comment
 *
 * @category    Class */
// * @description CompanyManagementSummary
/**
 * @package     Spinen\ConnectWise\Clients\Company
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CompanyManagementSummaryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CompanyManagementSummary"
     */
    public function testCompanyManagementSummary()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "management_solution"
     */
    public function testPropertyManagementSolution()
    {

    }

    /**
     * Test attribute "group_identifier"
     */
    public function testPropertyGroupIdentifier()
    {

    }

    /**
     * Test attribute "device_type"
     */
    public function testPropertyDeviceType()
    {

    }

    /**
     * Test attribute "agreement"
     */
    public function testPropertyAgreement()
    {

    }

    /**
     * Test attribute "snmp_machines"
     */
    public function testPropertySnmpMachines()
    {

    }

    /**
     * Test attribute "total_workstations"
     */
    public function testPropertyTotalWorkstations()
    {

    }

    /**
     * Test attribute "total_servers"
     */
    public function testPropertyTotalServers()
    {

    }

    /**
     * Test attribute "total_windows_servers"
     */
    public function testPropertyTotalWindowsServers()
    {

    }

    /**
     * Test attribute "total_windows_workstations"
     */
    public function testPropertyTotalWindowsWorkstations()
    {

    }

    /**
     * Test attribute "total_managed_machines"
     */
    public function testPropertyTotalManagedMachines()
    {

    }

    /**
     * Test attribute "servers_offline"
     */
    public function testPropertyServersOffline()
    {

    }

    /**
     * Test attribute "servers_disk_space_low"
     */
    public function testPropertyServersDiskSpaceLow()
    {

    }

    /**
     * Test attribute "failed_backup_jobs"
     */
    public function testPropertyFailedBackupJobs()
    {

    }

    /**
     * Test attribute "total_notifications"
     */
    public function testPropertyTotalNotifications()
    {

    }

    /**
     * Test attribute "successful_backup_jobs"
     */
    public function testPropertySuccessfulBackupJobs()
    {

    }

    /**
     * Test attribute "server_availability"
     */
    public function testPropertyServerAvailability()
    {

    }

    /**
     * Test attribute "viruses_removed"
     */
    public function testPropertyVirusesRemoved()
    {

    }

    /**
     * Test attribute "spyware_items_removed"
     */
    public function testPropertySpywareItemsRemoved()
    {

    }

    /**
     * Test attribute "windows_patches_installed"
     */
    public function testPropertyWindowsPatchesInstalled()
    {

    }

    /**
     * Test attribute "disk_cleanups"
     */
    public function testPropertyDiskCleanups()
    {

    }

    /**
     * Test attribute "disk_defragmentations"
     */
    public function testPropertyDiskDefragmentations()
    {

    }

    /**
     * Test attribute "fully_patched_machines"
     */
    public function testPropertyFullyPatchedMachines()
    {

    }

    /**
     * Test attribute "missing_one_two_patches_machines"
     */
    public function testPropertyMissingOneTwoPatchesMachines()
    {

    }

    /**
     * Test attribute "missing_three_five_patches_machines"
     */
    public function testPropertyMissingThreeFivePatchesMachines()
    {

    }

    /**
     * Test attribute "missing_more_five_patches_machines"
     */
    public function testPropertyMissingMoreFivePatchesMachines()
    {

    }

    /**
     * Test attribute "missing_unscanned_patches_machines"
     */
    public function testPropertyMissingUnscannedPatchesMachines()
    {

    }

    /**
     * Test attribute "alerts_generated"
     */
    public function testPropertyAlertsGenerated()
    {

    }

    /**
     * Test attribute "internet_connectivity"
     */
    public function testPropertyInternetConnectivity()
    {

    }

    /**
     * Test attribute "disk_space_cleaned_mb"
     */
    public function testPropertyDiskSpaceCleanedMb()
    {

    }

    /**
     * Test attribute "missing_security_patches"
     */
    public function testPropertyMissingSecurityPatches()
    {

    }

    /**
     * Test attribute "cpu_utilization"
     */
    public function testPropertyCpuUtilization()
    {

    }

    /**
     * Test attribute "memory_utilization"
     */
    public function testPropertyMemoryUtilization()
    {

    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
