<?php
/**
 * CompanyStatusTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Company
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Company API
 *
 * ConnectWise Company API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Company;

/**
 * CompanyStatusTest Class Doc Comment
 *
 * @category    Class */
// * @description CompanyStatus
/**
 * @package     Spinen\ConnectWise\Clients\Company
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CompanyStatusTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CompanyStatus"
     */
    public function testCompanyStatus()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "default_flag"
     */
    public function testPropertyDefaultFlag()
    {

    }

    /**
     * Test attribute "inactive_flag"
     */
    public function testPropertyInactiveFlag()
    {

    }

    /**
     * Test attribute "notify_flag"
     */
    public function testPropertyNotifyFlag()
    {

    }

    /**
     * Test attribute "disallow_saving_flag"
     */
    public function testPropertyDisallowSavingFlag()
    {

    }

    /**
     * Test attribute "notification_message"
     */
    public function testPropertyNotificationMessage()
    {

    }

    /**
     * Test attribute "custom_note_flag"
     */
    public function testPropertyCustomNoteFlag()
    {

    }

    /**
     * Test attribute "cancel_open_tracks_flag"
     */
    public function testPropertyCancelOpenTracksFlag()
    {

    }

    /**
     * Test attribute "track"
     */
    public function testPropertyTrack()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
