<?php
/**
 * ConfigurationQuestionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Company
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Company API
 *
 * ConnectWise Company API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Company;

/**
 * ConfigurationQuestionTest Class Doc Comment
 *
 * @category    Class */
// * @description ConfigurationQuestion
/**
 * @package     Spinen\ConnectWise\Clients\Company
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConfigurationQuestionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ConfigurationQuestion"
     */
    public function testConfigurationQuestion()
    {

    }

    /**
     * Test attribute "answer_id"
     */
    public function testPropertyAnswerId()
    {

    }

    /**
     * Test attribute "question_id"
     */
    public function testPropertyQuestionId()
    {

    }

    /**
     * Test attribute "question"
     */
    public function testPropertyQuestion()
    {

    }

    /**
     * Test attribute "answer"
     */
    public function testPropertyAnswer()
    {

    }

    /**
     * Test attribute "sequence_number"
     */
    public function testPropertySequenceNumber()
    {

    }

    /**
     * Test attribute "number_of_decimals"
     */
    public function testPropertyNumberOfDecimals()
    {

    }

    /**
     * Test attribute "field_type"
     */
    public function testPropertyFieldType()
    {

    }

    /**
     * Test attribute "required_flag"
     */
    public function testPropertyRequiredFlag()
    {

    }

}
