<?php
/**
 * ConfigurationTypeQuestionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Company
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Company API
 *
 * ConnectWise Company API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Company;

/**
 * ConfigurationTypeQuestionTest Class Doc Comment
 *
 * @category    Class */
// * @description ConfigurationTypeQuestion
/**
 * @package     Spinen\ConnectWise\Clients\Company
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConfigurationTypeQuestionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ConfigurationTypeQuestion"
     */
    public function testConfigurationTypeQuestion()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "configuration_type_id"
     */
    public function testPropertyConfigurationTypeId()
    {

    }

    /**
     * Test attribute "field_type"
     */
    public function testPropertyFieldType()
    {

    }

    /**
     * Test attribute "entry_type"
     */
    public function testPropertyEntryType()
    {

    }

    /**
     * Test attribute "sequence_number"
     */
    public function testPropertySequenceNumber()
    {

    }

    /**
     * Test attribute "question"
     */
    public function testPropertyQuestion()
    {

    }

    /**
     * Test attribute "number_of_decimals"
     */
    public function testPropertyNumberOfDecimals()
    {

    }

    /**
     * Test attribute "required_flag"
     */
    public function testPropertyRequiredFlag()
    {

    }

    /**
     * Test attribute "inactive_flag"
     */
    public function testPropertyInactiveFlag()
    {

    }

    /**
     * Test attribute "possible_answers"
     */
    public function testPropertyPossibleAnswers()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
