<?php
/**
 * ConfigurationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Company
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Company API
 *
 * ConnectWise Company API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Company;

/**
 * ConfigurationTest Class Doc Comment
 *
 * @category    Class */
// * @description Configuration
/**
 * @package     Spinen\ConnectWise\Clients\Company
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConfigurationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Configuration"
     */
    public function testConfiguration()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {

    }

    /**
     * Test attribute "contact"
     */
    public function testPropertyContact()
    {

    }

    /**
     * Test attribute "site"
     */
    public function testPropertySite()
    {

    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {

    }

    /**
     * Test attribute "business_unit_id"
     */
    public function testPropertyBusinessUnitId()
    {

    }

    /**
     * Test attribute "device_identifier"
     */
    public function testPropertyDeviceIdentifier()
    {

    }

    /**
     * Test attribute "serial_number"
     */
    public function testPropertySerialNumber()
    {

    }

    /**
     * Test attribute "model_number"
     */
    public function testPropertyModelNumber()
    {

    }

    /**
     * Test attribute "tag_number"
     */
    public function testPropertyTagNumber()
    {

    }

    /**
     * Test attribute "purchase_date"
     */
    public function testPropertyPurchaseDate()
    {

    }

    /**
     * Test attribute "installation_date"
     */
    public function testPropertyInstallationDate()
    {

    }

    /**
     * Test attribute "installed_by"
     */
    public function testPropertyInstalledBy()
    {

    }

    /**
     * Test attribute "warranty_expiration_date"
     */
    public function testPropertyWarrantyExpirationDate()
    {

    }

    /**
     * Test attribute "vendor_notes"
     */
    public function testPropertyVendorNotes()
    {

    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {

    }

    /**
     * Test attribute "mac_address"
     */
    public function testPropertyMacAddress()
    {

    }

    /**
     * Test attribute "last_login_name"
     */
    public function testPropertyLastLoginName()
    {

    }

    /**
     * Test attribute "bill_flag"
     */
    public function testPropertyBillFlag()
    {

    }

    /**
     * Test attribute "backup_successes"
     */
    public function testPropertyBackupSuccesses()
    {

    }

    /**
     * Test attribute "backup_incomplete"
     */
    public function testPropertyBackupIncomplete()
    {

    }

    /**
     * Test attribute "backup_failed"
     */
    public function testPropertyBackupFailed()
    {

    }

    /**
     * Test attribute "backup_restores"
     */
    public function testPropertyBackupRestores()
    {

    }

    /**
     * Test attribute "last_backup_date"
     */
    public function testPropertyLastBackupDate()
    {

    }

    /**
     * Test attribute "backup_server_name"
     */
    public function testPropertyBackupServerName()
    {

    }

    /**
     * Test attribute "backup_billable_space_gb"
     */
    public function testPropertyBackupBillableSpaceGb()
    {

    }

    /**
     * Test attribute "backup_protected_device_list"
     */
    public function testPropertyBackupProtectedDeviceList()
    {

    }

    /**
     * Test attribute "backup_year"
     */
    public function testPropertyBackupYear()
    {

    }

    /**
     * Test attribute "backup_month"
     */
    public function testPropertyBackupMonth()
    {

    }

    /**
     * Test attribute "ip_address"
     */
    public function testPropertyIpAddress()
    {

    }

    /**
     * Test attribute "default_gateway"
     */
    public function testPropertyDefaultGateway()
    {

    }

    /**
     * Test attribute "os_type"
     */
    public function testPropertyOsType()
    {

    }

    /**
     * Test attribute "os_info"
     */
    public function testPropertyOsInfo()
    {

    }

    /**
     * Test attribute "cpu_speed"
     */
    public function testPropertyCpuSpeed()
    {

    }

    /**
     * Test attribute "ram"
     */
    public function testPropertyRam()
    {

    }

    /**
     * Test attribute "local_hard_drives"
     */
    public function testPropertyLocalHardDrives()
    {

    }

    /**
     * Test attribute "parent_configuration_id"
     */
    public function testPropertyParentConfigurationId()
    {

    }

    /**
     * Test attribute "vendor"
     */
    public function testPropertyVendor()
    {

    }

    /**
     * Test attribute "manufacturer"
     */
    public function testPropertyManufacturer()
    {

    }

    /**
     * Test attribute "questions"
     */
    public function testPropertyQuestions()
    {

    }

    /**
     * Test attribute "active_flag"
     */
    public function testPropertyActiveFlag()
    {

    }

    /**
     * Test attribute "management_link"
     */
    public function testPropertyManagementLink()
    {

    }

    /**
     * Test attribute "remote_link"
     */
    public function testPropertyRemoteLink()
    {

    }

    /**
     * Test attribute "sla"
     */
    public function testPropertySla()
    {

    }

    /**
     * Test attribute "mobile_guid"
     */
    public function testPropertyMobileGuid()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

    /**
     * Test attribute "display_vendor_flag"
     */
    public function testPropertyDisplayVendorFlag()
    {

    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {

    }

}
