<?php
/**
 * ContactCommunicationsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Company
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Company API
 *
 * ConnectWise Company API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Company;

use \Spinen\ConnectWise\Clients\Company\Configuration;
use \Spinen\ConnectWise\Clients\Company\ApiClient;
use \Spinen\ConnectWise\Clients\Company\ApiException;
use \Spinen\ConnectWise\Clients\Company\ObjectSerializer;

/**
 * ContactCommunicationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Company
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ContactCommunicationsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for companyContactsIdCommunicationsCommunicationIdDelete
     *
     * .
     *
     */
    public function testCompanyContactsIdCommunicationsCommunicationIdDelete()
    {

    }

    /**
     * Test case for companyContactsIdCommunicationsCommunicationIdGet
     *
     * .
     *
     */
    public function testCompanyContactsIdCommunicationsCommunicationIdGet()
    {

    }

    /**
     * Test case for companyContactsIdCommunicationsCommunicationIdPatch
     *
     * .
     *
     */
    public function testCompanyContactsIdCommunicationsCommunicationIdPatch()
    {

    }

    /**
     * Test case for companyContactsIdCommunicationsCommunicationIdPut
     *
     * .
     *
     */
    public function testCompanyContactsIdCommunicationsCommunicationIdPut()
    {

    }

    /**
     * Test case for companyContactsIdCommunicationsCountGet
     *
     * .
     *
     */
    public function testCompanyContactsIdCommunicationsCountGet()
    {

    }

    /**
     * Test case for companyContactsIdCommunicationsGet
     *
     * .
     *
     */
    public function testCompanyContactsIdCommunicationsGet()
    {

    }

    /**
     * Test case for companyContactsIdCommunicationsPost
     *
     * .
     *
     */
    public function testCompanyContactsIdCommunicationsPost()
    {

    }

}
