<?php
/**
 * ManagementEmailsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Company
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Company API
 *
 * ConnectWise Company API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Company;

use \Spinen\ConnectWise\Clients\Company\Configuration;
use \Spinen\ConnectWise\Clients\Company\ApiClient;
use \Spinen\ConnectWise\Clients\Company\ApiException;
use \Spinen\ConnectWise\Clients\Company\ObjectSerializer;

/**
 * ManagementEmailsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Company
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ManagementEmailsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for companyManagementEmailsCountGet
     *
     * .
     *
     */
    public function testCompanyManagementEmailsCountGet()
    {

    }

    /**
     * Test case for companyManagementEmailsGet
     *
     * .
     *
     */
    public function testCompanyManagementEmailsGet()
    {

    }

    /**
     * Test case for companyManagementEmailsIdDelete
     *
     * .
     *
     */
    public function testCompanyManagementEmailsIdDelete()
    {

    }

    /**
     * Test case for companyManagementEmailsIdGet
     *
     * .
     *
     */
    public function testCompanyManagementEmailsIdGet()
    {

    }

    /**
     * Test case for companyManagementEmailsIdPatch
     *
     * .
     *
     */
    public function testCompanyManagementEmailsIdPatch()
    {

    }

    /**
     * Test case for companyManagementEmailsIdPut
     *
     * .
     *
     */
    public function testCompanyManagementEmailsIdPut()
    {

    }

    /**
     * Test case for companyManagementEmailsPost
     *
     * .
     *
     */
    public function testCompanyManagementEmailsPost()
    {

    }

}
