<?php
/**
 * OwnershipTypesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Company
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Company API
 *
 * ConnectWise Company API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Company;

use \Spinen\ConnectWise\Clients\Company\Configuration;
use \Spinen\ConnectWise\Clients\Company\ApiClient;
use \Spinen\ConnectWise\Clients\Company\ApiException;
use \Spinen\ConnectWise\Clients\Company\ObjectSerializer;

/**
 * OwnershipTypesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Company
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OwnershipTypesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for companyOwnershipTypesCountGet
     *
     * .
     *
     */
    public function testCompanyOwnershipTypesCountGet()
    {

    }

    /**
     * Test case for companyOwnershipTypesGet
     *
     * .
     *
     */
    public function testCompanyOwnershipTypesGet()
    {

    }

    /**
     * Test case for companyOwnershipTypesIdDelete
     *
     * .
     *
     */
    public function testCompanyOwnershipTypesIdDelete()
    {

    }

    /**
     * Test case for companyOwnershipTypesIdGet
     *
     * .
     *
     */
    public function testCompanyOwnershipTypesIdGet()
    {

    }

    /**
     * Test case for companyOwnershipTypesIdPatch
     *
     * .
     *
     */
    public function testCompanyOwnershipTypesIdPatch()
    {

    }

    /**
     * Test case for companyOwnershipTypesIdPut
     *
     * .
     *
     */
    public function testCompanyOwnershipTypesIdPut()
    {

    }

    /**
     * Test case for companyOwnershipTypesPost
     *
     * .
     *
     */
    public function testCompanyOwnershipTypesPost()
    {

    }

}
